name: dashboard
description: Dashboard

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'
  amazon_cognito_identity_dart_2: ^0.1.25+2

  rounded_loading_button: ^1.0.18
  another_flushbar: ^1.10.15
  transformer_page_view: ^0.1.6
  font_awesome_flutter: ^9.1.0
  quiver: ^3.0.1
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.2
  public_suffix: ^2.0.1
  rflutter_alert: ^1.1.0
  syncfusion_flutter_datagrid: ^18.4.47-beta
  flutter_svg: ^0.19.3
  flutter_easyloading: ^3.0.0
  progress_indicator_button: ^0.0.3
  flutter_spinkit: ^5.0.0
  lottie: ^0.7.0+1
  multi_select_flutter: ^1.0.6
  flutter_spinbox: ^0.5.2
  flutter_login: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/adstart.svg
    - assets/images/white_orange.png
    - assets/images/black_orange.png
